/* derived.c: a list of derived channels
 *
 * This software is copyright (C) 2002-2010 University of Toronto
 *
 * This file is part of the BLAST flight code licensed under the GNU
 * General Public License.
 *
 * You should have received a copy of the GNU General Public License
 * along with this software; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

/* !XXX!!XXX!!XXX!!XXX!!XXX!! BIG ALL CAPS WARNING !!XXX!!XXX!!XXX!!XXX!!XXX!!
 *
 * IF YOU ADD, MODIFY, OR DELETE *ANY* CHANNELS IN THIS FILE YOU *MUST*
 * RECOMPILE AND RESTART THE DECOM DAEMON (DECOMD) ON ARWEN!
 *
 * !XXX!!XXX!!XXX!!XXX!!XXX!! BIG ALL CAPS WARNING !!XXX!!XXX!!XXX!!XXX!!XXX!!
 */

#include "derived.h"

/* Don's Handy Guide to adding derived channels:
 *
 * There are seven types of derived channels which can be added to the format
 * file.  Channel names are, of course, case sensitive.  On start-up, both
 * mcp and decomd run sanity checks on the channel lists, including the derived
 * channel list.  The checks will fail for the derived channel list if either
 * a source channel doesn't exist or a derived channel has a name already in
 * use.  Listed below are the derived channel types and their arguments.  If
 * more derived channel types are desired, please ask me to add them.  --dvw
 *
 * o LINCOM: Single field calibration.  Arguments:
 *   1.  Derived Channel Name (string)
 *   2.  Source Channel Name (string)
 *   3.  Calibration Slope (double)
 *   4.  Calibration Intercept (double)
 * o LINCOM2: Two field linear combination
 *   1.  Derived Channel Name (string)
 *   2.  Source 1 Channel Name (string)
 *   3.  Source 1 Calibration Slope (double)
 *   4.  Source 1 Calibration Intercept (double)
 *   5.  Source 2 Channel Name (string)
 *   6.  Source 2 Calibration Slope (double)
 *   7.  Source 2 Calibration Intercept (double)
 * o LINTERP: Linearly interpolated look up table
 *   1.  Derived Channel Name (string)
 *   2.  Source Channel Name (string)
 *   3.  Full Path to Look Up Table File (string)
 * o BITS: A bit channel extracted from a larger source channel
 *   1.  Derived Channel Name (string)
 *   2.  Source Channel Name (string)
 *   3.  First bit of the bitword, numbered from zero (integer)
 *   4.  Length of the bitword (integer)
 * o COMMENT: A literal comment to be inserted into the format file
 *   1.  Comment Text (string) -- there is no need to include the comment
 *       delimiter (#).
 * o UNITS: meta data defining units and quantity for existing fields
 *   1.  Source Channel Name (string)
 *   2.  String for the quantity (eg "Temperature")
 *   3.  String for the Units (eg, "^oC")
 *
 *
 * In addition to the derived channels derived below, defile will add the
 * "Nice CPU Values" (to wit: CPU_SEC, CPU_HOUR, etc.), properly offset to the
 * start of the file, to the end of the format file.
 */

#define LUT_DIR "/data/etc/blast/"
// offset looks like 500mV which gets multiplied up by 5 in mx+b
// This offset may be due to the relay board or the design of the
// Hall sensors themselves. We may change this later.
// TODO(ian): check that this is correct once PBOBs assembled
#define CURR_LOOP_OFFSET -2.5000

derived_tng_t derived_list[] = {
    /* Pointing */
    COMMENT("Microsecond Resolution Time"),
    LINCOM2("Time", "time_usec", 1.0E-6, 0, "time", 1, 0),
    UNITS("Time", "Time", "s"),

    COMMENT("General BLAST Status"),
    BITWORD("SOUTH_I_AM", "status_mcc", 0, 1),
    BITWORD("AT_FLOAT", "status_mcc", 1, 1),
    BITWORD("UPLINK_SCHED", "status_mcc", 2, 1),
    BITWORD("BLAST_SUCKS", "status_mcc", 3, 1),
    BITWORD("SCHEDULE", "status_mcc", 4, 3),
    BITWORD("INCHARGE", "status_mcc", 7, 1),
    BITWORD("SLOT_SCHED", "status_mcc", 8, 8),

#ifndef BOLOTEST
    COMMENT("Pointing Stuff"),
    LINCOM("X_H_P", "x_p", 0.0003662109375, 0),

    BITWORD("VETO_EL_MOTOR_ENC", "veto_sensor", 0, 1),
    BITWORD("VETO_XSC0", "veto_sensor", 1, 1),
    //    BITWORD("VETO_EL_ENC", "veto_sensor", 2, 1),
    //  (LMF 2018-12-20 not needed.  Can be used for another sensor.)
    BITWORD("VETO_MAG1", "veto_sensor", 3, 1),
    BITWORD("VETO_MAG2", "veto_sensor", 4, 1),
    BITWORD("VETO_EL_CLIN", "veto_sensor", 5, 1),
    BITWORD("VETO_XSC1", "veto_sensor", 6, 1),
    BITWORD("IS_SCHED", "veto_sensor", 7, 1),
    BITWORD("AZ_AUTO_GYRO", "veto_sensor", 8, 1),
    BITWORD("EL_AUTO_GYRO", "veto_sensor", 9, 1),
    BITWORD("DISABLE_EL", "veto_sensor", 10, 1),
    BITWORD("DISABLE_AZ", "veto_sensor", 11, 1),
    BITWORD("FORCE_EL", "veto_sensor", 12, 1),
    BITWORD("VETO_PSS", "veto_sensor", 13, 1),
    BITWORD("VETO_DGPS", "veto_sensor", 14, 1),
    COMMENT("ACS Digital Signals"),

    /* charge controller (CC) faults and alarms */
    COMMENT("Charge Controller Bitfields"),

    BITWORD("F_OVERCURRENT_CC1", "fault_cc1", 0, 1),
    BITWORD("F_FET_SHORT_CC1", "fault_cc1", 1, 1),
    BITWORD("F_SOFTWARE_BUG_CC1", "fault_cc1", 2, 1),
    BITWORD("F_BATT_HVD_CC1", "fault_cc1", 3, 1),
    BITWORD("F_ARR_HVD_CC1", "fault_cc1", 4, 1),
    BITWORD("F_DIP_CHANGED_CC1", "fault_cc1", 5, 1),
    BITWORD("F_SETTING_CHANGE_CC1", "fault_cc1", 6, 1),
    BITWORD("F_RTS_SHORT_CC1", "fault_cc1", 7, 1),
    BITWORD("F_RTS_DISCONN_CC1", "fault_cc1", 8, 1),
    BITWORD("F_EEPROM_LIM_CC1", "fault_cc1", 9, 1),
    BITWORD("F_SLAVE_TO_CC1", "fault_cc1", 10, 1),

    BITWORD("F_OVERCURRENT_CC2", "fault_cc2", 0, 1),
    BITWORD("F_FET_SHORT_CC2", "fault_cc2", 1, 1),
    BITWORD("F_SOFTWARE_BUG_CC2", "fault_cc2", 2, 1),
    BITWORD("F_BATT_HVD_CC2", "fault_cc2", 3, 1),
    BITWORD("F_ARR_HVD_CC2", "fault_cc2", 4, 1),
    BITWORD("F_DIP_CHANGED_CC2", "fault_cc2", 5, 1),
    BITWORD("F_SETTING_CHANGE_CC2", "fault_cc2", 6, 1),
    BITWORD("F_RTS_SHORT_CC2", "fault_cc2", 7, 1),
    BITWORD("F_RTS_DISCONN_CC2", "fault_cc2", 8, 1),
    BITWORD("F_EEPROM_LIM_CC2", "fault_cc2", 9, 1),
    BITWORD("F_SLAVE_TO_CC2", "fault_cc2", 10, 1),

    BITWORD("A_RTS_OPEN_CC1", "alarm_cc1", 0, 1),
    BITWORD("A_RTS_SHORT_CC1", "alarm_cc1", 1, 1),
    BITWORD("A_RTS_DISCONN_CC1", "alarm_cc1", 2, 1),
    BITWORD("A_TSENSE_OPEN_CC1", "alarm_cc1", 3, 1),
    BITWORD("A_TSENSE_SHORT_CC1", "alarm_cc1", 4, 1),
    BITWORD("A_HITEMP_LIM_CC1", "alarm_cc1", 5, 1),
    BITWORD("A_CURRENT_LIM_CC1", "alarm_cc1", 6, 1),
    BITWORD("A_CURRENT_OFFSET_CC1", "alarm_cc1", 7, 1),
    BITWORD("A_BATT_RANGE_CC1", "alarm_cc1", 8, 1),
    BITWORD("A_BATTSENSE_DISC_CC1", "alarm_cc1", 9, 1),
    BITWORD("A_UNCALIB_CC1", "alarm_cc1", 10, 1),
    BITWORD("A_RTS_MISWIRE_CC1", "alarm_cc1", 11, 1),
    BITWORD("A_HVD_CC1", "alarm_cc1", 12, 1),
    BITWORD("A_SYS_MISWIRE_CC1", "alarm_cc1", 14, 1),
    BITWORD("A_FET_OPEN_CC1", "alarm_cc1", 15, 1),

    BITWORD("A_RTS_OPEN_CC2", "alarm_cc2", 0, 1),
    BITWORD("A_RTS_SHORT_CC2", "alarm_cc2", 1, 1),
    BITWORD("A_RTS_DISCONN_CC2", "alarm_cc2", 2, 1),
    BITWORD("A_TSENSE_OPEN_CC2", "alarm_cc2", 3, 1),
    BITWORD("A_TSENSE_SHORT_CC2", "alarm_cc2", 4, 1),
    BITWORD("A_HITEMP_LIM_CC2", "alarm_cc2", 5, 1),
    BITWORD("A_CURRENT_LIM_CC2", "alarm_cc2", 6, 1),
    BITWORD("A_CURRENT_OFFSET_CC2", "alarm_cc2", 7, 1),
    BITWORD("A_BATT_RANGE_CC2", "alarm_cc2", 8, 1),
    BITWORD("A_BATTSENSE_DISC_CC2", "alarm_cc2", 9, 1),
    BITWORD("A_UNCALIB_CC2", "alarm_cc2", 10, 1),
    BITWORD("A_RTS_MISWIRE_CC2", "alarm_cc2", 11, 1),
    BITWORD("A_HVD_CC2", "alarm_cc2", 12, 1),
    BITWORD("A_SYS_MISWIRE_CC2", "alarm_cc2", 14, 1),
    BITWORD("A_FET_OPEN_CC2", "alarm_cc2", 15, 1),

    BITWORD("A_VP12_OFF_CC1", "alarm_cc1", 16, 1),
    BITWORD("C_A_HI_INPUT_LIM_CC1", "alarm_cc1", 17, 1),
    BITWORD("C_A_ADC_MAX_IN_CC1", "alarm_cc1", 18, 1),
    BITWORD("C_A_RESET_CC1", "alarm_cc1", 19, 1),

    BITWORD("A_VP12_OFF_CC2", "alarm_cc2", 16, 1),
    BITWORD("C_A_HI_INPUT_LIM_CC2", "alarm_cc2", 17, 1),
    BITWORD("C_A_ADC_MAX_IN_CC2", "alarm_cc2", 18, 1),
    BITWORD("C_A_RESET_CC2", "alarm_cc2", 19, 1),

    BITWORD("ACT0_INIT_ACTBUS", "status_actbus", 0, 1),
    BITWORD("ACT1_INIT_ACTBUS", "status_actbus", 1, 1),
    BITWORD("ACT2_INIT_ACTBUS", "status_actbus", 2, 1),
    BITWORD("BAL_INIT_ACTBUS", "status_actbus", 3, 1),
    BITWORD("LOCK_INIT_ACTBUS", "status_actbus", 4, 1),
    BITWORD("SHUTTER_INIT_ACTBUS", "status_actbus", 6, 1),
    BITWORD("PUMPED_POT_INIT_ACTBUS", "status_actbus", 7, 1),
    BITWORD("PUMP_VALVE_INIT_ACTBUS", "status_actbus", 8, 1),
    BITWORD("FILL_VALVE_INIT_ACTBUS", "status_actbus", 9, 1),

    BITWORD("DIR_BAL", "status_bal", 0, 2),
    BITWORD("INIT_BAL", "status_bal", 2, 1),
    BITWORD("DO_MOVE_BAL", "status_bal", 3, 1),
    BITWORD("MOVING_BAL", "status_bal", 4, 1),
    BITWORD("MODE_BAL", "status_bal", 5, 2),

      #endif

    COMMENT("Lock Motor/Actuators"),
    BITWORD("LS_OPEN_LOCK", "state_lock", 0, 1),
    BITWORD("LS_CLOSED_LOCK", "state_lock", 1, 1),
    BITWORD("LS_DRIVE_OFF_LOCK", "state_lock", 2, 1),
    BITWORD("LS_POT_RAIL_LOCK", "state_lock", 3, 1),
    BITWORD("LS_DRIVE_EXT_LOCK", "state_lock", 4, 1),
    BITWORD("LS_DRIVE_RET_LOCK", "state_lock", 5, 1),
    BITWORD("LS_DRIVE_STP_LOCK", "state_lock", 6, 1),
    BITWORD("LS_DRIVE_JIG_LOCK", "state_lock", 7, 1),
    BITWORD("LS_DRIVE_UNK_LOCK", "state_lock", 8, 1),
    BITWORD("LS_EL_OK_LOCK", "state_lock", 9, 1),
    BITWORD("LS_IGNORE_EL_LOCK", "state_lock", 10, 1),
    BITWORD("LS_DRIVE_FORCE_LOCK", "state_lock", 11, 1),

    //      ),

    /* Secondary Focus */
    COMMENT("Secondary Focus"),
    LINCOM2("REL_FOCUS_SF", "CORRECTION_SF", 1, 0, "OFFSET_SF", 1, 0),
    LINCOM2("VETO_SF", "WAIT_SF", 1, 0, "AGE_SF", -1, 0),

    LINCOM2("Pos_0_act", "POS_0_ACT", 1, 0, "OFFSET_0_ACT", 1, 0),
    LINCOM2("Pos_1_act", "POS_1_ACT", 1, 0, "OFFSET_1_ACT", 1, 0),
    LINCOM2("Pos_2_act", "POS_2_ACT", 1, 0, "OFFSET_2_ACT", 1, 0),
    LINCOM2("Enc_0_act", "ENC_0_ACT", 1, 0, "OFFSET_0_ACT", 1, 0),
    LINCOM2("Enc_1_act", "ENC_1_ACT", 1, 0, "OFFSET_1_ACT", 1, 0),
    LINCOM2("Enc_2_act", "ENC_2_ACT", 1, 0, "OFFSET_2_ACT", 1, 0),
    LINCOM2("Goal_0_act", "GOAL_0_ACT", 1, 0, "OFFSET_0_ACT", 1, 0),
    LINCOM2("Goal_1_act", "GOAL_1_ACT", 1, 0, "OFFSET_1_ACT", 1, 0),
    LINCOM2("Goal_2_act", "GOAL_2_ACT", 1, 0, "OFFSET_2_ACT", 1, 0),
    LINCOM2("Dr_0_act", "DR_0_ACT", 1, 0, "OFFSET_0_ACT", 1, 0),
    LINCOM2("Dr_1_act", "DR_1_ACT", 1, 0, "OFFSET_1_ACT", 1, 0),
    LINCOM2("Dr_2_act", "DR_2_ACT", 1, 0, "OFFSET_2_ACT", 1, 0),

    BITWORD("TRIM_WAIT_ACT", "flags_act", 0, 1),
    BITWORD("TRIMMED_ACT", "flags_act", 1, 1),
    BITWORD("BUSY_0_ACT", "flags_act", 2, 1),
    BITWORD("BUSY_1_ACT", "flags_act", 3, 1),
    BITWORD("BUSY_2_ACT", "flags_act", 4, 1),
    BITWORD("BAD_MOVE_ACT", "flags_act", 5, 1),

    BITWORD("LATCHED_DATA_CRC_EL", "latched_fault_el", 0, 1),
    BITWORD("LATCHED_AMP_INT_EL", "latched_fault_el", 1, 1),
    BITWORD("LATCHED_SHORT_CIRC_EL", "latched_fault_el", 2, 1),
    BITWORD("LATCHED_AMP_OVER_T_EL", "latched_fault_el", 3, 1),
    BITWORD("LATCHED_MOTOR_OVER_T_EL", "latched_fault_el", 4, 1),
    BITWORD("LATCHED_OVERVOLT_EL", "latched_fault_el", 5, 1),
    BITWORD("LATCHED_UNDERVOLT_EL", "latched_fault_el", 6, 1),
    BITWORD("LATCHED_FEEDBACK_EL", "latched_fault_el", 7, 1),
    BITWORD("LATCHED_PHASING_ERR_EL", "latched_fault_el", 8, 1),
    BITWORD("LATCHED_TRACKING_ERR_EL", "latched_fault_el", 9, 1),
    BITWORD("LATCHED_OVERCURRENT_EL", "latched_fault_el", 10, 1),
    BITWORD("LATCHED_FPGA_FAIL_EL", "latched_fault_el", 11, 1),
    BITWORD("LATCHED_CMD_INPUT_LOST_EL", "latched_fault_el", 12, 1),
    BITWORD("LATCHED_FPGA_FAIL2_EL", "latched_fault_el", 13, 1),
    BITWORD("LATCHED_SAFETY_CIRC_EL", "latched_fault_el", 14, 1),
    BITWORD("LATCHED_CONT_CURRENT_EL", "latched_fault_el", 15, 1),

    BITWORD("LATCHED_DATA_CRC_PIV", "latched_fault_piv", 0, 1),
    BITWORD("LATCHED_AMP_INT_PIV", "latched_fault_piv", 1, 1),
    BITWORD("LATCHED_SHORT_CIRC_PIV", "latched_fault_piv", 2, 1),
    BITWORD("LATCHED_AMP_OVER_T_PIV", "latched_fault_piv", 3, 1),
    BITWORD("LATCHED_MOTOR_OVER_T_PIV", "latched_fault_piv", 4, 1),
    BITWORD("LATCHED_OVERVOLT_PIV", "latched_fault_piv", 5, 1),
    BITWORD("LATCHED_UNDERVOLT_PIV", "latched_fault_piv", 6, 1),
    BITWORD("LATCHED_FEEDBACK_PIV", "latched_fault_piv", 7, 1),
    BITWORD("LATCHED_PHASING_ERR_PIV", "latched_fault_piv", 8, 1),
    BITWORD("LATCHED_TRACKING_ERR_PIV", "latched_fault_piv", 9, 1),
    BITWORD("LATCHED_OVERCURRENT_PIV", "latched_fault_piv", 10, 1),
    BITWORD("LATCHED_FPGA_FAIL_PIV", "latched_fault_piv", 11, 1),
    BITWORD("LATCHED_CMD_INPUT_LOST_PIV", "latched_fault_piv", 12, 1),
    BITWORD("LATCHED_FPGA_FAIL2_PIV", "latched_fault_piv", 13, 1),
    BITWORD("LATCHED_SAFETY_CIRC_PIV", "latched_fault_piv", 14, 1),
    BITWORD("LATCHED_CONT_CURRENT_PIV", "latched_fault_piv", 15, 1),

    BITWORD("LATCHED_DATA_CRC_RW", "latched_fault_rw", 0, 1),
    BITWORD("LATCHED_AMP_INT_RW", "latched_fault_rw", 1, 1),
    BITWORD("LATCHED_SHORT_CIRC_RW", "latched_fault_rw", 2, 1),
    BITWORD("LATCHED_AMP_OVER_T_RW", "latched_fault_rw", 3, 1),
    BITWORD("LATCHED_MOTOR_OVER_T_RW", "latched_fault_rw", 4, 1),
    BITWORD("LATCHED_OVERVOLT_RW", "latched_fault_rw", 5, 1),
    BITWORD("LATCHED_UNDERVOLT_RW", "latched_fault_rw", 6, 1),
    BITWORD("LATCHED_FEEDBACK_RW", "latched_fault_rw", 7, 1),
    BITWORD("LATCHED_PHASING_ERR_RW", "latched_fault_rw", 8, 1),
    BITWORD("LATCHED_TRACKING_ERR_RW", "latched_fault_rw", 9, 1),
    BITWORD("LATCHED_OVERCURRENT_RW", "latched_fault_rw", 10, 1),
    BITWORD("LATCHED_FPGA_FAIL_RW", "latched_fault_rw", 11, 1),
    BITWORD("LATCHED_CMD_INPUT_LOST_RW", "latched_fault_rw", 12, 1),
    BITWORD("LATCHED_FPGA_FAIL2_RW", "latched_fault_rw", 13, 1),
    BITWORD("LATCHED_SAFETY_CIRC_RW", "latched_fault_rw", 14, 1),
    BITWORD("LATCHED_CONT_CURRENT_RW", "latched_fault_rw", 15, 1),

    BITWORD("ST_SHORT_CIRC_EL", "status_el", 0, 1),
    BITWORD("ST_AMP_OVER_T_EL", "status_el", 1, 1),
    BITWORD("ST_OVER_V_EL", "status_el", 2, 1),
    BITWORD("ST_UNDER_V_EL", "status_el", 3, 1),

    BITWORD("ST_FEEDBACK_ERR_EL", "status_el", 5, 1),
    BITWORD("ST_MOT_PHAS_ERR_EL", "status_el", 6, 1),
    BITWORD("ST_I_LIMITED_EL", "status_el", 7, 1),
    BITWORD("ST_VOLT_LIM_EL", "status_el", 8, 1),
    BITWORD("ST_LIM_SW_POS_EL", "status_el", 9, 1),
    BITWORD("ST_LIM_SW_NEG_EL", "status_el", 10, 1),

    BITWORD("ST_DISAB_HWARE_EL", "status_el", 11, 1),
    BITWORD("ST_DISAB_SWARE_EL", "status_el", 12, 1),
    BITWORD("ST_ATTEMPT_STOP_EL", "status_el", 13, 1),
    BITWORD("ST_MOT_BREAK_ACT_EL", "status_el", 14, 1),
    BITWORD("ST_PWM_OUT_DIS_EL", "status_el", 15, 1),
    BITWORD("ST_POS_SOFT_LIM_EL", "status_el", 16, 1),
    BITWORD("ST_NEG_SOFT_LIM_EL", "status_el", 17, 1),
    BITWORD("ST_FOLLOW_ERR_EL", "status_el", 18, 1),
    BITWORD("ST_FOLLOW_WARN_EL", "status_el", 19, 1),
    BITWORD("ST_AMP_HAS_RESET_EL", "status_el", 20, 1),
    BITWORD("ST_ENCODER_WRAP_EL", "status_el", 21, 1),
    BITWORD("ST_AMP_FAULT_EL", "status_el", 22, 1),
    BITWORD("ST_VEL_LIMITED_EL", "status_el", 23, 1),
    BITWORD("ST_ACCEL_LIMITED_EL", "status_el", 24, 1),

    BITWORD("ST_IN_MOTION_EL", "status_el", 27, 1),
    BITWORD("ST_V_OUT_TRACK_W_EL", "status_el", 28, 1),
    BITWORD("ST_PHASE_NOT_INIT_EL", "status_el", 29, 1),

    BITWORD("ST_SHORT_CIRC_PIV", "status_piv", 0, 1),
    BITWORD("ST_AMP_OVER_T_PIV", "status_piv", 1, 1),
    BITWORD("ST_OVER_V_PIV", "status_piv", 2, 1),
    BITWORD("ST_UNDER_V_PIV", "status_piv", 3, 1),

    BITWORD("ST_FEEDBACK_ERR_PIV", "status_piv", 5, 1),
    BITWORD("ST_MOT_PHAS_ERR_PIV", "status_piv", 6, 1),
    BITWORD("ST_I_LIMITED_PIV", "status_piv", 7, 1),
    BITWORD("ST_VOLT_LIM_PIV", "status_piv", 8, 1),
    BITWORD("ST_LIM_SW_POS_PIV", "status_piv", 9, 1),
    BITWORD("ST_LIM_SW_NEG_PIV", "status_piv", 10, 1),

    BITWORD("ST_DISAB_HWARE_PIV", "status_piv", 11, 1),
    BITWORD("ST_DISAB_SWARE_PIV", "status_piv", 12, 1),
    BITWORD("ST_ATTEMPT_STOP_PIV", "status_piv", 13, 1),
    BITWORD("ST_MOT_BREAK_ACT_PIV", "status_piv", 14, 1),
    BITWORD("ST_PWM_OUT_DIS_PIV", "status_piv", 15, 1),
    BITWORD("ST_POS_SOFT_LIM_PIV", "status_piv", 16, 1),
    BITWORD("ST_NEG_SOFT_LIM_PIV", "status_piv", 17, 1),
    BITWORD("ST_FOLLOW_ERR_PIV", "status_piv", 18, 1),
    BITWORD("ST_FOLLOW_WARN_PIV", "status_piv", 19, 1),
    BITWORD("ST_AMP_HAS_RESET_PIV", "status_piv", 20, 1),
    BITWORD("ST_ENCODER_WRAP_PIV", "status_piv", 21, 1),
    BITWORD("ST_AMP_FAULT_PIV", "status_piv", 22, 1),
    BITWORD("ST_VEL_LIMITED_PIV", "status_piv", 23, 1),
    BITWORD("ST_ACCEL_LIMITED_PIV", "status_piv", 24, 1),

    BITWORD("ST_IN_MOTION_PIV", "status_piv", 27, 1),
    BITWORD("ST_V_OUT_TRACK_W_PIV", "status_piv", 28, 1),
    BITWORD("ST_PHASE_NOT_INIT_PIV", "status_piv", 29, 1),

    BITWORD("ST_SHORT_CIRC_RW", "status_rw", 0, 1),
    BITWORD("ST_AMP_OVER_T_RW", "status_rw", 1, 1),
    BITWORD("ST_OVER_V_RW", "status_rw", 2, 1),
    BITWORD("ST_UNDER_V_RW", "status_rw", 3, 1),

    BITWORD("ST_FEEDBACK_ERR_RW", "status_rw", 5, 1),
    BITWORD("ST_MOT_PHAS_ERR_RW", "status_rw", 6, 1),
    BITWORD("ST_I_LIMITED_RW", "status_rw", 7, 1),
    BITWORD("ST_VOLT_LIM_RW", "status_rw", 8, 1),
    BITWORD("ST_LIM_SW_POS_RW", "status_rw", 9, 1),
    BITWORD("ST_LIM_SW_NEG_RW", "status_rw", 10, 1),

    BITWORD("ST_DISAB_HWARE_RW", "status_rw", 11, 1),
    BITWORD("ST_DISAB_SWARE_RW", "status_rw", 12, 1),
    BITWORD("ST_ATTEMPT_STOP_RW", "status_rw", 13, 1),
    BITWORD("ST_MOT_BREAK_ACT_RW", "status_rw", 14, 1),
    BITWORD("ST_PWM_OUT_DIS_RW", "status_rw", 15, 1),
    BITWORD("ST_POS_SOFT_LIM_RW", "status_rw", 16, 1),
    BITWORD("ST_NEG_SOFT_LIM_RW", "status_rw", 17, 1),
    BITWORD("ST_FOLLOW_ERR_RW", "status_rw", 18, 1),
    BITWORD("ST_FOLLOW_WARN_RW", "status_rw", 19, 1),
    BITWORD("ST_AMP_HAS_RESET_RW", "status_rw", 20, 1),
    BITWORD("ST_ENCODER_WRAP_RW", "status_rw", 21, 1),
    BITWORD("ST_AMP_FAULT_RW", "status_rw", 22, 1),
    BITWORD("ST_VEL_LIMITED_RW", "status_rw", 23, 1),
    BITWORD("ST_ACCEL_LIMITED_RW", "status_rw", 24, 1),

    BITWORD("ST_IN_MOTION_RW", "status_rw", 27, 1),
    BITWORD("ST_V_OUT_TRACK_W_RW", "status_rw", 28, 1),
    BITWORD("ST_PHASE_NOT_INIT_RW", "status_rw", 29, 1),
    BITWORD("NET_ST_NODE_STATUS_RW", "network_status_rw", 0, 2),
    BITWORD("NET_ST_SYNC_MISSING_RW", "network_status_rw", 4, 1),
    BITWORD("NET_ST_GUARD_ERR_RW", "network_status_rw", 5, 1),
    BITWORD("NET_ST_BUS_OFF_RW", "network_status_rw", 8, 1),
    BITWORD("NET_ST_SYNC_TRANS_ERROR_RW", "network_status_rw", 9, 1),
    BITWORD("NET_ST_SYNC_REC_ERROR_RW", "network_status_rw", 10, 1),
    BITWORD("NET_ST_SYNC_TRANS_WARNING_RW", "network_status_rw", 11, 1),
    BITWORD("NET_ST_SYNC_REC_WARNING_RW", "network_status_rw", 12, 1),
    BITWORD("STATE_READY_EL", "state_el", 0, 1),
    BITWORD("STATE_SWITCHED_ON_EL", "state_el", 1, 1),
    BITWORD("STATE_OP_ENABLED_EL", "state_el", 2, 1),
    BITWORD("STATE_FAULT_EL", "state_el", 3, 1),
    BITWORD("STATE_VOLTAGE_ENABLED_EL", "state_el", 4, 1),
    BITWORD("STATE_NOT_QUICK_STOP_EL", "state_el", 5, 1),
    BITWORD("STATE_ON_DISABLE_EL", "state_el", 6, 1),
    BITWORD("STATE_WARNING_EL", "state_el", 7, 1),
    BITWORD("STATE_ABORTED_EL", "state_el", 8, 1),
    BITWORD("STATE_REMOTE_EL", "state_el", 9, 1),
    BITWORD("STATE_ON_TARGET_EL", "state_el", 10, 1),
    BITWORD("STATE_AMP_LIMIT_EL", "state_el", 11, 1),
    BITWORD("STATE_MOVING_EL", "state_el", 14, 1),
    BITWORD("NET_ST_NODE_STATUS_EL", "network_status_el", 0, 2),
    BITWORD("NET_ST_SYNC_MISSING_EL", "network_status_el", 4, 1),
    BITWORD("NET_ST_GUARD_ERR_EL", "network_status_el", 5, 1),
    BITWORD("NET_ST_BUS_OFF_EL", "network_status_el", 8, 1),
    BITWORD("NET_ST_SYNC_TRANS_ERROR_EL", "network_status_el", 9, 1),
    BITWORD("NET_ST_SYNC_REC_ERROR_EL", "network_status_el", 10, 1),
    BITWORD("NET_ST_SYNC_TRANS_WARNING_EL", "network_status_el", 11, 1),
    BITWORD("NET_ST_SYNC_REC_WARNING_EL", "network_status_el", 12, 1),
    BITWORD("STATE_READY_RW", "state_rw", 0, 1),
    BITWORD("STATE_SWITCHED_ON_RW", "state_rw", 1, 1),
    BITWORD("STATE_OP_ENABLED_RW", "state_rw", 2, 1),
    BITWORD("STATE_FAULT_RW", "state_rw", 3, 1),
    BITWORD("STATE_VOLTAGE_ENABLED_RW", "state_rw", 4, 1),
    BITWORD("STATE_NOT_QUICK_STOP_RW", "state_rw", 5, 1),
    BITWORD("STATE_ON_DISABLE_RW", "state_rw", 6, 1),
    BITWORD("STATE_WARNING_RW", "state_rw", 7, 1),
    BITWORD("STATE_ABORTED_RW", "state_rw", 8, 1),
    BITWORD("STATE_REMOTE_RW", "state_rw", 9, 1),
    BITWORD("STATE_ON_TARGET_RW", "state_rw", 10, 1),
    BITWORD("STATE_AMP_LIMIT_RW", "state_rw", 11, 1),
    BITWORD("STATE_MOVING_RW", "state_rw", 14, 1),

    BITWORD("STATE_READY_PIV", "state_piv", 0, 1),
    BITWORD("STATE_SWITCHED_ON_PIV", "state_piv", 1, 1),
    BITWORD("STATE_OP_ENABLED_PIV", "state_piv", 2, 1),
    BITWORD("STATE_FAULT_PIV", "state_piv", 3, 1),
    BITWORD("STATE_VOLTAGE_ENABLED_PIV", "state_piv", 4, 1),
    BITWORD("STATE_NOT_QUICK_STOP_PIV", "state_piv", 5, 1),
    BITWORD("STATE_ON_DISABLE_PIV", "state_piv", 6, 1),
    BITWORD("STATE_WARNING_PIV", "state_piv", 7, 1),
    BITWORD("STATE_ABORTED_PIV", "state_piv", 8, 1),
    BITWORD("STATE_REMOTE_PIV", "state_piv", 9, 1),
    BITWORD("STATE_ON_TARGET_PIV", "state_piv", 10, 1),
    BITWORD("STATE_AMP_LIMIT_PIV", "state_piv", 11, 1),
    BITWORD("STATE_MOVING_PIV", "state_piv", 14, 1),
    BITWORD("NET_ST_NODE_STATUS_PIV", "network_status_piv", 0, 2),
    BITWORD("NET_ST_SYNC_MISSING_PIV", "network_status_piv", 4, 1),
    BITWORD("NET_ST_GUARD_ERR_PIV", "network_status_piv", 5, 1),
    BITWORD("NET_ST_BUS_OFF_PIV", "network_status_piv", 8, 1),
    BITWORD("NET_ST_SYNC_TRANS_ERROR_PIV", "network_status_piv", 9, 1),
    BITWORD("NET_ST_SYNC_REC_ERROR_PIV", "network_status_piv", 10, 1),
    BITWORD("NET_ST_SYNC_TRANS_WARNING_PIVOT", "network_status_piv", 11, 1),
    BITWORD("NET_ST_SYNC_REC_WARNING_PIVOT", "network_status_piv", 12, 1),
    BITWORD("MC_EC_CMD_RESET", "mc_cmd_status", 0, 1),
    BITWORD("MC_EC_CMD_FIX_RW", "mc_cmd_status", 1, 1),
    BITWORD("MC_EC_CMD_FIX_EL", "mc_cmd_status", 2, 1),
    BITWORD("MC_EC_CMD_FIX_PIV", "mc_cmd_status", 3, 1),
    BITWORD("SLAVE_INDEX_EC_RW", "status_ec_rw", 0, 3),
    BITWORD("COMMS_OK_EC_RW", "status_ec_rw", 3, 1),
    BITWORD("SLAVE_ERROR_EC_RW", "status_ec_rw", 4, 1),
    BITWORD("HAS_DC_EC_RW", "status_ec_rw", 5, 1),
    BITWORD("IS_MC_EC_RW", "status_ec_rw", 6, 1),
    BITWORD("SLAVE_INDEX_EC_EL", "status_ec_el", 0, 3),
    BITWORD("COMMS_OK_EC_EL", "status_ec_el", 3, 1),
    BITWORD("SLAVE_ERROR_EC_EL", "status_ec_el", 4, 1),
    BITWORD("HAS_DC_EC_EL", "status_ec_el", 5, 1),
    BITWORD("IS_MC_EC_EL", "status_ec_el", 6, 1),
    BITWORD("SLAVE_INDEX_EC_PIV", "status_ec_piv", 0, 3),
    BITWORD("COMMS_OK_EC_PIV", "status_ec_piv", 3, 1),
    BITWORD("SLAVE_ERROR_EC_PIV", "status_ec_piv", 4, 1),
    BITWORD("HAS_DC_EC_PIV", "status_ec_piv", 5, 1),
    BITWORD("IS_MC_EC_PIV", "status_ec_piv", 6, 1),
    BITWORD("CTL_ON_READ_PIV", "control_word_read_piv", 0, 1),
    BITWORD("CTL_ENABLE_VOLTAGE_READ_PIV", "control_word_read_piv", 1, 1),
    BITWORD("CTL_QUICK_STOP_READ_PIV", "control_word_read_piv", 2, 1),
    BITWORD("CTL_ENABLE_READ_PIV", "control_word_read_piv", 3, 1),
    BITWORD("CTL_MODE_OF_OPERATION_READ_PIV", "control_word_read_piv", 4, 3),
    BITWORD("CTL_RESET_FAULT_READ_PIV", "control_word_read_piv", 7, 1),
    BITWORD("CTL_HALT_READ_PIV", "control_word_read_piv", 8, 1),
    BITWORD("CTL_ON_WRITE_PIV", "control_word_write_piv", 0, 1),
    BITWORD("CTL_ENABLE_VOLTAGE_WRITE_PIV", "control_word_write_piv", 1, 1),
    BITWORD("CTL_QUICK_STOP_WRITE_PIV", "control_word_write_piv", 2, 1),
    BITWORD("CTL_ENABLE_WRITE_PIV", "control_word_write_piv", 3, 1),
    BITWORD("CTL_MODE_OF_OPERATION_WRITE_PIV", "control_word_write_piv", 4, 3),
    BITWORD("CTL_RESET_FAULT_WRITE_PIV", "control_word_write_piv", 7, 1),
    BITWORD("CTL_HALT_WRITE_PIV", "control_word_write_piv", 8, 1),
    BITWORD("CTL_ON_READ_EL", "control_word_read_el", 0, 1),
    BITWORD("CTL_ENABLE_VOLTAGE_READ_EL", "control_word_read_el", 1, 1),
    BITWORD("CTL_QUICK_STOP_READ_EL", "control_word_read_el", 2, 1),
    BITWORD("CTL_ENABLE_READ_EL", "control_word_read_el", 3, 1),
    BITWORD("CTL_MODE_OF_OPERATION_READ_EL", "control_word_read_el", 4, 3),
    BITWORD("CTL_RESET_FAULT_READ_EL", "control_word_read_el", 7, 1),
    BITWORD("CTL_HALT_READ_EL", "control_word_read_el", 8, 1),
    BITWORD("CTL_ON_WRITE_EL", "control_word_write_el", 0, 1),
    BITWORD("CTL_ENABLE_VOLTAGE_WRITE_EL", "control_word_write_el", 1, 1),
    BITWORD("CTL_QUICK_STOP_WRITE_EL", "control_word_write_el", 2, 1),
    BITWORD("CTL_ENABLE_WRITE_EL", "control_word_write_el", 3, 1),
    BITWORD("CTL_MODE_OF_OPERATION_WRITE_EL", "control_word_write_el", 4, 3),
    BITWORD("CTL_RESET_FAULT_WRITE_EL", "control_word_write_el", 7, 1),
    BITWORD("CTL_HALT_WRITE_EL", "control_word_write_rw", 8, 1),
    BITWORD("CTL_ON_READ_RW", "control_word_read_rw", 0, 1),
    BITWORD("CTL_ENABLE_VOLTAGE_READ_RW", "control_word_read_rw", 1, 1),
    BITWORD("CTL_QUICK_STOP_READ_RW", "control_word_read_rw", 2, 1),
    BITWORD("CTL_ENABLE_READ_RW", "control_word_read_rw", 3, 1),
    BITWORD("CTL_MODE_OF_OPERATION_READ_RW", "control_word_read_rw", 4, 3),
    BITWORD("CTL_RESET_FAULT_READ_RW", "control_word_read_rw", 7, 1),
    BITWORD("CTL_HALT_READ_RW", "control_word_read_rw", 8, 1),
    BITWORD("CTL_ON_WRITE_RW", "control_word_write_rw", 0, 1),
    BITWORD("CTL_ENABLE_VOLTAGE_WRITE_RW", "control_word_write_rw", 1, 1),
    BITWORD("CTL_QUICK_STOP_WRITE_RW", "control_word_write_rw", 2, 1),
    BITWORD("CTL_ENABLE_WRITE_RW", "control_word_write_rw", 3, 1),
    BITWORD("CTL_MODE_OF_OPERATION_WRITE_RW", "control_word_write_rw", 4, 3),
    BITWORD("CTL_RESET_FAULT_WRITE_RW", "control_word_write_rw", 7, 1),
    BITWORD("CTL_HALT_WRITE_RW", "control_word_write_rw", 8, 1),

    // Various LabJack channels
    // voltage monitoring
    LINCOM("Outer_frame_voltage_1", "OUTER_FRAME_VM_1", 10, 0),
    LINCOM("Outer_frame_voltage_2", "OUTER_FRAME_VM_2", 10, 0),
    LINCOM("Outer_frame_voltage_3", "OUTER_FRAME_VM_3", 10, 0),
    LINCOM("Inner_frame_voltage_1", "INNER_FRAME_VM_1", 10, 0),
    LINCOM("Inner_frame_voltage_2", "INNER_FRAME_VM_2", 10, 0),
    LINCOM("Inner_frame_voltage_3", "INNER_FRAME_VM_3", 10, 0),

    // current monitoring
    LINCOM("Current_fc1", "current_fc1", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_fc2", "current_fc2", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_of_eth", "current_of_eth", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_motor_lj", "current_motor_box_lj", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_of_unassigned_1", "current_unassigned", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_of_inclinometer", "current_of_inclinometer", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_magnetometer", "current_magnetometers", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_gondola_thermometry", "current_gondola_thermometry", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_gps_ntp", "current_gps_ntp", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_pss_box", "current_pss_box", 5, CURR_LOOP_OFFSET),

    LINCOM("Current_sc1", "current_sc1", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_cryo_digital", "current_cryo_digital", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_gyros", "current_gyros", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_rfsoc", "current_rfsoc", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_if_eth", "current_if_eth", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_steppers", "current_steppers", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_if_inclinometer", "current_if_inclinometer", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_sc2", "current_sc2", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_cryo_analog", "current_cryo_analog", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_last_resort_valve", "current_unassigned", 5, CURR_LOOP_OFFSET),

    // thermistors
    // resistances
    LINTERP("Therm1_R", "THERMISTOR_1", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm2_R", "THERMISTOR_2", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm3_R", "THERMISTOR_3", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm4_R", "THERMISTOR_4", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm5_R", "THERMISTOR_5", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm6_R", "THERMISTOR_6", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm7_R", "THERMISTOR_7", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm8_R", "THERMISTOR_8", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm9_R", "THERMISTOR_9", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm10_R", "THERMISTOR_10", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm11_R", "THERMISTOR_11", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm12_R", "THERMISTOR_12", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm13_R", "THERMISTOR_13", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm14_R", "THERMISTOR_14", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm15_R", "THERMISTOR_15", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm16_R", "THERMISTOR_16", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm17_R", "THERMISTOR_17", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm18_R", "THERMISTOR_18", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm19_R", "THERMISTOR_19", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm20_R", "THERMISTOR_20", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm21_R", "THERMISTOR_21", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm22_R", "THERMISTOR_22", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm23_R", "THERMISTOR_23", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm24_R", "THERMISTOR_24", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm25_R", "THERMISTOR_25", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm26_R", "THERMISTOR_26", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm27_R", "THERMISTOR_27", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm28_R", "THERMISTOR_28", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm29_R", "THERMISTOR_29", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm30_R", "THERMISTOR_30", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm31_R", "THERMISTOR_31", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm32_R", "THERMISTOR_32", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm33_R", "THERMISTOR_33", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm34_R", "THERMISTOR_34", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm35_R", "THERMISTOR_35", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm36_R", "THERMISTOR_36", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm37_R", "THERMISTOR_37", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm38_R", "THERMISTOR_38", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm39_R", "THERMISTOR_39", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm40_R", "THERMISTOR_40", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm41_R", "THERMISTOR_41", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm42_R", "THERMISTOR_42", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm43_R", "THERMISTOR_43", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm44_R", "THERMISTOR_44", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm45_R", "THERMISTOR_45", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm46_R", "THERMISTOR_46", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm47_R", "THERMISTOR_47", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm48_R", "THERMISTOR_48", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm49_R", "THERMISTOR_49", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm50_R", "THERMISTOR_50", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm51_R", "THERMISTOR_51", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm52_R", "THERMISTOR_52", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm53_R", "THERMISTOR_53", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm54_R", "THERMISTOR_54", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm55_R", "THERMISTOR_55", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm56_R", "THERMISTOR_56", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm57_R", "THERMISTOR_57", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm58_R", "THERMISTOR_58", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm59_R", "THERMISTOR_59", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm60_R", "THERMISTOR_60", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm61_R", "THERMISTOR_61", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm62_R", "THERMISTOR_62", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm63_R", "THERMISTOR_63", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm64_R", "THERMISTOR_64", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm65_R", "THERMISTOR_65", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm66_R", "THERMISTOR_66", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm67_R", "THERMISTOR_67", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm68_R", "THERMISTOR_68", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm69_R", "THERMISTOR_69", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm70_R", "THERMISTOR_70", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm71_R", "THERMISTOR_71", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm72_R", "THERMISTOR_72", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm73_R", "THERMISTOR_73", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm74_R", "THERMISTOR_74", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm75_R", "THERMISTOR_75", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm76_R", "THERMISTOR_76", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm77_R", "THERMISTOR_77", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm78_R", "THERMISTOR_78", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm79_R", "THERMISTOR_79", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm80_R", "THERMISTOR_80", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm81_R", "THERMISTOR_81", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm82_R", "THERMISTOR_82", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm83_R", "THERMISTOR_83", LUT_DIR "Thermistor_VtoR.lut"),
    LINTERP("Therm84_R", "THERMISTOR_84", LUT_DIR "Thermistor_VtoR.lut"),
    // Temperatures
    LINTERP("Therm1_T", "Therm1_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm2_T", "Therm2_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm3_T", "Therm3_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm4_T", "Therm4_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm5_T", "Therm5_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm6_T", "Therm6_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm7_T", "Therm7_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm8_T", "Therm8_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm9_T", "Therm9_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm10_T", "Therm10_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm11_T", "Therm11_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm12_T", "Therm12_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm13_T", "Therm13_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm14_T", "Therm14_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm15_T", "Therm15_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm16_T", "Therm16_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm17_T", "Therm17_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm18_T", "Therm18_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm19_T", "Therm19_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm20_T", "Therm20_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm21_T", "Therm21_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm22_T", "Therm22_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm23_T", "Therm23_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm24_T", "Therm24_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm25_T", "Therm25_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm26_T", "Therm26_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm27_T", "Therm27_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm28_T", "Therm28_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm29_T", "Therm29_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm30_T", "Therm30_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm31_T", "Therm31_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm32_T", "Therm32_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm33_T", "Therm33_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm34_T", "Therm34_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm35_T", "Therm35_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm36_T", "Therm36_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm37_T", "Therm37_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm38_T", "Therm38_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm39_T", "Therm39_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm40_T", "Therm40_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm41_T", "Therm41_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm42_T", "Therm42_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm43_T", "Therm43_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm44_T", "Therm44_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm45_T", "Therm45_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm46_T", "Therm46_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm47_T", "Therm47_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm48_T", "Therm48_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm49_T", "Therm49_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm50_T", "Therm50_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm51_T", "Therm51_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm52_T", "Therm52_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm53_T", "Therm53_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm54_T", "Therm54_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm55_T", "Therm55_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm56_T", "Therm56_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm57_T", "Therm57_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm58_T", "Therm58_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm59_T", "Therm59_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm60_T", "Therm60_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm61_T", "Therm61_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm62_T", "Therm62_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm63_T", "Therm63_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm64_T", "Therm64_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm65_T", "Therm65_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm66_T", "Therm66_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm67_T", "Therm67_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm68_T", "Therm68_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm69_T", "Therm69_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm70_T", "Therm70_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm71_T", "Therm71_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm72_T", "Therm72_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm73_T", "Therm73_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm74_T", "Therm74_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm75_T", "Therm75_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm76_T", "Therm76_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm77_T", "Therm77_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm78_T", "Therm78_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm79_T", "Therm79_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm80_T", "Therm80_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm81_T", "Therm81_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm82_T", "Therm82_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm83_T", "Therm83_R", LUT_DIR "Thermistor_RtoT.lut"),
    LINTERP("Therm84_T", "Therm84_R", LUT_DIR "Thermistor_RtoT.lut"),

    LINCOM("Current_fc1", "CURRENT_FC1", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_fc2", "CURRENT_FC2", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_of_eth", "CURRENT_OF_ETH", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_motor_lj", "CURRENT_MOTOR_BOX_LJ", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_of_unassigned_1", "CURRENT_UNASSIGNED", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_of_inclinometer", "CURRENT_OF_INCLINOMETER", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_magnetometer", "CURRENT_MAGNETOMETERS", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_gondola_thermometry", "CURRENT_GONDOLA_THERMOMETRY", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_gps_ntp", "CURRENT_GPS_NTP", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_pss_box", "CURRENT_PSS_BOX", 5, CURR_LOOP_OFFSET),

    LINCOM("Current_sc1", "CURRENT_SC1", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_cryo_digital", "CURRENT_CRYO_DIGITAL", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_gyros", "CURRENT_GYROS", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_rfsoc", "CURRENT_RFSOC", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_if_eth", "CURRENT_IF_ETH", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_steppers", "CURRENT_STEPPERS", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_if_inclinometer", "CURRENT_IF_INCLINOMETER", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_sc2", "CURRENT_SC2", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_cryo_analog", "CURRENT_CRYO_ANALOG", 5, CURR_LOOP_OFFSET),
    LINCOM("Current_last_resort_valve", "CURRENT_UNASSIGNED", 5, CURR_LOOP_OFFSET),

    // Roach Channels
    // may be a reference for status channels for TIM
    // BITWORD("SCAN_RETUNE_TOP_TRIGGER_ROACH", "scan_retune_trigger_roach", 0, 1),
    // BITWORD("SCAN_RETUNE_BOTTOM_TRIGGER_ROACH", "scan_retune_trigger_roach", 1, 1),

    // we may want these as a reference for RFSoC status channels
    /*
    BITWORD("HAS_QDR_CAL_ROACH5", "status_roach5", 0, 1),
    BITWORD("FULL_LOOP_FAIL_ROACH5", "status_roach5", 1, 1),
    BITWORD("HAS_TARG_TONES_ROACH5", "status_roach5", 2, 1),
    BITWORD("IS_STREAMING_ROACH5", "status_roach5", 3, 1),
    BITWORD("IS_SWEEPING_ROACH5", "status_roach5", 4, 2),
    BITWORD("HAS_VNA_SWEEP_ROACH5", "status_roach5", 6, 1),
    BITWORD("HAS_TARG_SWEEP_ROACH5", "status_roach5", 7, 1),
    BITWORD("WRITE_FLAG_ROACH5", "status_roach5", 8, 1),
    BITWORD("HAS_REF_PARAMS_ROACH5", "status_roach5", 9, 1),
    BITWORD("EXT_REF_ROACH5", "status_roach5", 10, 1),
    BITWORD("HAS_VNA_TONES_ROACH5", "status_roach5", 11, 1),
    BITWORD("SWEEP_FAIL_ROACH5", "status_roach5", 12, 1),
    BITWORD("QDR_CAL_FAIL_ROACH5", "status_roach5", 13, 1),
    BITWORD("FIRMWARE_UPLOAD_FAIL_ROACH5", "status_roach5", 14, 1),
    BITWORD("HAS_FIRMWARE_ROACH5", "status_roach5", 15, 1),
    BITWORD("TONE_FINDING_ERROR_ROACH5", "status_roach5", 16, 2),
    BITWORD("KATCP_CONNECT_ERROR_ROACH5", "status_roach5", 18, 1),
    BITWORD("IS_COMPRESSING_ROACH5", "status_roach5", 19, 1),
    BITWORD("DOING_FULL_LOOP_ROACH5", "status_roach5", 20, 1),
    BITWORD("DOING_FIND_KIDS_LOOP_ROACH5", "status_roach5", 21, 1),
    BITWORD("IS_FINDING_KIDS_ROACH5", "status_roach5", 22, 1),
    BITWORD("TRNAROUND_LOOP_FAIL_ROACH5", "status_roach5", 23, 1),
    BITWORD("DOING_TURNAROUND_LOOP_ROACH5", "status_roach5", 24, 1),
    BITWORD("AUTO_ALLOW_TRNAROUND_LOOP_ROACH5", "status_roach5", 25, 1),
    BITWORD("ALLOW_CHOP_LO_ROACH5", "status_roach5", 26, 1),
    // BITWORD("IS_CHOPPING_LO_ROACH5", "status_roach5", 27, 1),
    BITWORD("PI_REBOOT_WARNING_ROACH5", "status_roach5", 28, 1),
    BITWORD("DATA_STREAM_ERROR_ROACH5", "status_roach5", 29, 1),
    BITWORD("WAITING_FOR_LAMP_ROACH5", "status_roach5", 30, 1),
    BITWORD("HAS_LAMP_CONTROL_ROACH5", "status_roach5", 31, 1),
     */

    // status channels
    // thermistors below!
    // Kept as a reference for future channels
    // LINTERP("Rt_therm1", "THERMISTOR_1", LUT_DIR "Thermistor_VtoR.lut"),
    // LINTERP("Tt_if_front", "Rt_therm1", LUT_DIR "Thermistor_RtoT.lut"),

    // Kept as a reference for future channels
    // BITWORD("Labjack0_conn_status", "labjack_conn_status", 0, 1),

    BITWORD("TRIGGER_XSC0", "trigger_xsc", 0, 1),
    BITWORD("TRIGGER_XSC1", "trigger_xsc", 1, 1),
    BITWORD("TRIGGER_STATE_XSC", "trigger_xsc", 2, 6),

    END_OF_DERIVED_CHANNELS};
